<?php
// SPDX-License-Identifier: BSD-3-Clause

/** Autogenerated by `bump build`; do not edit this file. **/
define('ROOT', realpath(__DIR__ . '/../'));
const FRAMEWORK_DIR = ROOT . '/vendor/aklump/composer-repository-framework/';





